/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package project;

import Custom.Connector;
import Custom.ConnectorH;
import com.formdev.flatlaf.FlatLightLaf;
import com.formdev.flatlaf.extras.FlatSVGIcon;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.Map;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author OZ
 */
public class AddBarang extends javax.swing.JDialog {
private JDialog previousDialog;
    /**
     * Creates new form AddBarangD
     */
    public AddBarang(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
        ComboPelanggan(Jc_Nama);
        setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
    @Override
        public void windowClosing(java.awt.event.WindowEvent e) {
        Bt_BatalActionPerformed(null);
    }
});
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Lb_Nama = new javax.swing.JLabel();
        Lb_Jenis = new javax.swing.JLabel();
        Lb_Merk = new javax.swing.JLabel();
        Tf_Merk = new javax.swing.JTextField();
        Bt_Simpan = new javax.swing.JButton();
        Bt_Batal = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Lb_Bahan = new javax.swing.JLabel();
        Tf_Bahan = new javax.swing.JTextField();
        Lb_Warna = new javax.swing.JLabel();
        Tf_Warna = new javax.swing.JTextField();
        Jc_Jenis = new javax.swing.JComboBox<>();
        Jc_Nama = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        Lb_Nama.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Lb_Nama.setText("Nama Pelanggan");

        Lb_Jenis.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Lb_Jenis.setText("Jenis Barang");

        Lb_Merk.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Lb_Merk.setText("Merk");

        Tf_Merk.setBackground(new java.awt.Color(233, 231, 231));
        Tf_Merk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tf_MerkActionPerformed(evt);
            }
        });

        Bt_Simpan.setBackground(new java.awt.Color(51, 51, 255));
        Bt_Simpan.setForeground(new java.awt.Color(255, 255, 255));
        Bt_Simpan.setText("Berikutnya");
        Bt_Simpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Bt_SimpanMouseClicked(evt);
            }
        });
        Bt_Simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_SimpanActionPerformed(evt);
            }
        });

        Bt_Batal.setBackground(new java.awt.Color(204, 0, 0));
        Bt_Batal.setForeground(new java.awt.Color(255, 255, 255));
        Bt_Batal.setText("Batal");
        Bt_Batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_BatalActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Century751 No2 BT", 1, 16)); // NOI18N
        jLabel1.setText("Tambah Barang");

        Lb_Bahan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Lb_Bahan.setText("Jenis Bahan");

        Tf_Bahan.setBackground(new java.awt.Color(233, 231, 231));
        Tf_Bahan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tf_BahanActionPerformed(evt);
            }
        });

        Lb_Warna.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Lb_Warna.setText("Warna");

        Tf_Warna.setBackground(new java.awt.Color(233, 231, 231));
        Tf_Warna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tf_WarnaActionPerformed(evt);
            }
        });

        Jc_Jenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Jenis Barang", "Sepatu", "Tas", "Topi" }));

        Jc_Nama.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Pelanggan" }));
        Jc_Nama.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(233, 231, 231), 2));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Jc_Nama, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Jc_Jenis, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(Lb_Bahan)
                        .addComponent(Tf_Bahan)
                        .addComponent(Lb_Warna)
                        .addComponent(Tf_Warna)
                        .addComponent(Lb_Jenis)
                        .addComponent(Lb_Merk)
                        .addComponent(Tf_Merk, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Lb_Nama))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(Bt_Simpan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Bt_Batal, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Lb_Nama)
                .addGap(12, 12, 12)
                .addComponent(Jc_Nama, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Lb_Jenis)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Jc_Jenis, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Lb_Merk)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Tf_Merk, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Lb_Bahan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Tf_Bahan, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Lb_Warna)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Tf_Warna, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Bt_Simpan)
                    .addComponent(Bt_Batal))
                .addGap(51, 51, 51))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Tf_MerkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tf_MerkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tf_MerkActionPerformed

    private void Bt_SimpanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Bt_SimpanMouseClicked
        if(!AntiKosong()) {
            return;
        }
        SaveData();
        AddOrder Trez = new AddOrder((java.awt.Frame)this.getParent(), true);
        if (previousDialog != null) {
            previousDialog.dispose();
        }
        this.dispose(); 
        Trez.setVisible(true);
    }//GEN-LAST:event_Bt_SimpanMouseClicked

    private void Bt_SimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_SimpanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Bt_SimpanActionPerformed

    private void Tf_BahanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tf_BahanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tf_BahanActionPerformed

    private void Tf_WarnaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tf_WarnaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tf_WarnaActionPerformed

    private void Bt_BatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_BatalActionPerformed
        MainAdd mainAdd = MainAdd.getInstance();
    if (mainAdd != null) {
        mainAdd.setVisible(true);
    }
    this.dispose(); 
    
    
    if (previousDialog != null) {
        previousDialog.dispose();
    }
    }//GEN-LAST:event_Bt_BatalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        FlatLightLaf.setup();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AddBarang dialog = new AddBarang(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bt_Batal;
    private javax.swing.JButton Bt_Simpan;
    private javax.swing.JComboBox<String> Jc_Jenis;
    private javax.swing.JComboBox<String> Jc_Nama;
    private javax.swing.JLabel Lb_Bahan;
    private javax.swing.JLabel Lb_Jenis;
    private javax.swing.JLabel Lb_Merk;
    private javax.swing.JLabel Lb_Nama;
    private javax.swing.JLabel Lb_Warna;
    private javax.swing.JTextField Tf_Bahan;
    private javax.swing.JTextField Tf_Merk;
    private javax.swing.JTextField Tf_Warna;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
 public void setPreviousDialog(JDialog dialog) {
        this.previousDialog = dialog;
    }
    public void ComboPelanggan(JComboBox<String> comboBox){
    
    DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
    Map<String, Integer> MapId = new HashMap<>();
    
    
    String sql = "SELECT id_pelanggan, nama FROM pelanggan";
    
    try (Connection conn = ConnectorH.getConnection();
            PreparedStatement pst = conn.prepareStatement(sql);
        ResultSet rs = pst.executeQuery()) {
        model.addElement("--Pilih Pelanggan--");
        while (rs.next()) {
            int Id= rs.getInt("id_pelanggan");
            String Nama = rs.getString("nama");
            model.addElement(Nama);
            MapId.put(Nama, Id);
        }
        
        
        
        comboBox.setModel(model);
        comboBox.putClientProperty("MapId", MapId);
        
    } catch (SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Gagal memuat data: " + e.getMessage());
    } 
}
public int PilihId(JComboBox<String> comboBox) {
    Map<String, Integer> MapId = (Map<String, Integer>) comboBox.getClientProperty("MapId");
    String selected = (String) comboBox.getSelectedItem();
    return (selected != null && MapId != null) ? MapId.getOrDefault(selected, -1) : -1; 
}

    private boolean AntiKosong(){
    if (Tf_Merk.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Merk barang tidak boleh kosong!");
        return false;
    }
    return true;
    }
    
    private void SaveData(){
     String JenisBarang = (String) Jc_Jenis.getSelectedItem();   
    int idPelanggan = PilihId(Jc_Nama);
 try {
            Connection con =  ConnectorH.getConnection();
            String query = "INSERT INTO barang "
                                + "(jenis_barang, merk, jenis_bahan, warna, id_pelanggan) "
                                + "VALUES (?, ?, ?, ?, ?)";
            PreparedStatement ps = con.prepareStatement(query);
            
            
            ps.setString(1, JenisBarang);
            ps.setString(2, Tf_Merk.getText());
            ps.setString(3, Tf_Bahan.getText());
            ps.setString(4, Tf_Warna.getText());
            ps.setInt(5, idPelanggan);
          
            
            
            
            ps.executeUpdate();
            JOptionPane.showMessageDialog(this, "Data berhasil disimpan!");
            
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Kesalahan pada database: " + e.getMessage());
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(this, "Koneksi database tidak tersedia!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal menyimpan data: " + e.getMessage());
        }
        ClearInput();
}

private void ClearInput(){
    // Jc_Nama.setText("");
    //Jc_Jenis
    Tf_Merk.setText("");
    Tf_Bahan.setText("");
    Tf_Warna.setText("");
}
}
