/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package project;

import Custom.Connector;
import com.formdev.flatlaf.FlatLightLaf;
import com.formdev.flatlaf.extras.FlatSVGIcon;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author OZ
 */
public class AddCust extends javax.swing.JDialog {
private boolean NewCustomer;
    /**
     * Creates new form AddCustD
     */
    public AddCust(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
        setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
    @Override
        public void windowClosing(java.awt.event.WindowEvent e) {
        Bt_BatalActionPerformed(null);
    }
});
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Lb_Nama = new javax.swing.JLabel();
        Tf_Nama = new javax.swing.JTextField();
        Lb_NoHP = new javax.swing.JLabel();
        Tf_NoHP = new javax.swing.JTextField();
        Lb_Alamat = new javax.swing.JLabel();
        Tf_Alamat = new javax.swing.JTextField();
        Bt_Simpan = new javax.swing.JButton();
        Bt_Batal = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        Lb_Nama.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Lb_Nama.setText("Nama");

        Tf_Nama.setBackground(new java.awt.Color(233, 231, 231));
        Tf_Nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tf_NamaActionPerformed(evt);
            }
        });

        Lb_NoHP.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Lb_NoHP.setText("No. Handphone");

        Tf_NoHP.setBackground(new java.awt.Color(233, 231, 231));
        Tf_NoHP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tf_NoHPActionPerformed(evt);
            }
        });

        Lb_Alamat.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Lb_Alamat.setText("Alamat");

        Tf_Alamat.setBackground(new java.awt.Color(233, 231, 231));
        Tf_Alamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tf_AlamatActionPerformed(evt);
            }
        });

        Bt_Simpan.setBackground(new java.awt.Color(51, 51, 255));
        Bt_Simpan.setForeground(new java.awt.Color(255, 255, 255));
        Bt_Simpan.setText("Berikutnya");
        Bt_Simpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Bt_SimpanMouseClicked(evt);
            }
        });

        Bt_Batal.setBackground(new java.awt.Color(204, 0, 0));
        Bt_Batal.setForeground(new java.awt.Color(255, 255, 255));
        Bt_Batal.setText("Batal");
        Bt_Batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_BatalActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Century751 No2 BT", 1, 16)); // NOI18N
        jLabel1.setText("Tambah Pelanggan");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Bt_Simpan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Bt_Batal, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Lb_Nama)
                    .addComponent(Tf_Nama, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lb_NoHP)
                    .addComponent(Tf_NoHP, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lb_Alamat)
                    .addComponent(Tf_Alamat, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(Lb_Nama)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Tf_Nama, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Lb_NoHP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Tf_NoHP, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Lb_Alamat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Tf_Alamat, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 125, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Bt_Simpan)
                    .addComponent(Bt_Batal))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Tf_NamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tf_NamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tf_NamaActionPerformed

    private void Tf_NoHPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tf_NoHPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tf_NoHPActionPerformed

    private void Tf_AlamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tf_AlamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tf_AlamatActionPerformed

    private void Bt_SimpanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Bt_SimpanMouseClicked
        if(!AntiKosong()) {
            return;
        }
        SaveData();
        NewCustomer = true;
        AddBarang Doz = new AddBarang((java.awt.Frame)this.getParent(), true);
        Doz.setPreviousDialog(this);
        this.dispose(); 
        Doz.setVisible(true);
    }//GEN-LAST:event_Bt_SimpanMouseClicked

    private void Bt_BatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_BatalActionPerformed
        MainAdd mainAdd = MainAdd.getInstance();
    if (mainAdd != null) {
        mainAdd.setVisible(true);
    }
    this.dispose();
    }//GEN-LAST:event_Bt_BatalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddCust.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddCust.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddCust.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddCust.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        FlatLightLaf.setup();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AddCust dialog = new AddCust(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bt_Batal;
    private javax.swing.JButton Bt_Simpan;
    private javax.swing.JLabel Lb_Alamat;
    private javax.swing.JLabel Lb_Nama;
    private javax.swing.JLabel Lb_NoHP;
    private javax.swing.JTextField Tf_Alamat;
    private javax.swing.JTextField Tf_Nama;
    private javax.swing.JTextField Tf_NoHP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
private boolean AntiKosong(){
       if (Tf_Nama.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Nama barang tidak boleh kosong!");
        return false;
    }

    if (Tf_NoHP.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Merk barang tidak boleh kosong!");
        return false;
    } 
    if (Tf_Alamat.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Merk barang tidak boleh kosong!");
        return false;
    }
    return true;
    }
    
    private void SaveData(){
 try {
            Connection con =  Connector.getkoneksi();
            String query = "INSERT INTO pelanggan (nama, no_hp, alamat) VALUES (?, ?, ?)";
            PreparedStatement ps = con.prepareStatement(query);
            
            
            ps.setString(1, Tf_Nama.getText());
            ps.setString(2, Tf_NoHP.getText());
            ps.setString(3, Tf_Alamat.getText());
          
            
            
            
            ps.executeUpdate();
            JOptionPane.showMessageDialog(this, "Data berhasil disimpan!");
            
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Kesalahan pada database: " + e.getMessage());
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(this, "Koneksi database tidak tersedia!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal menyimpan data: " + e.getMessage());
        }
 ClearInput();
}
private void ClearInput(){
    Tf_Nama.setText("");
    Tf_NoHP.setText("");
    Tf_Alamat.setText("");
}
}
