/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package project;
import java.awt.Frame;
/**
 *
 * @author OZ
 */
public class MainAdd extends javax.swing.JDialog {
private static MainAdd instance;
private AddOrder.OrderListener orderListener;
    /**
     * Creates new form MainAdd2
     */
    public void setOrderListener(AddOrder.OrderListener listener) {
        this.orderListener = listener;
        }
    public MainAdd(java.awt.Frame parent) {
        super(parent, false);
        initComponents();
        setLocationRelativeTo(parent);
        instance = this;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Bt_Pelanggan = new javax.swing.JButton();
        Bt_Pesanan = new javax.swing.JButton();
        Bt_Barang = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        Bt_Pelanggan.setBackground(new java.awt.Color(51, 153, 255));
        Bt_Pelanggan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Bt_Pelanggan.setForeground(new java.awt.Color(255, 255, 255));
        Bt_Pelanggan.setText("Pelanggan");
        Bt_Pelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_PelangganActionPerformed(evt);
            }
        });

        Bt_Pesanan.setBackground(new java.awt.Color(51, 51, 255));
        Bt_Pesanan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Bt_Pesanan.setForeground(new java.awt.Color(255, 255, 255));
        Bt_Pesanan.setText("Pesanan");
        Bt_Pesanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_PesananActionPerformed(evt);
            }
        });

        Bt_Barang.setBackground(new java.awt.Color(255, 204, 0));
        Bt_Barang.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Bt_Barang.setForeground(new java.awt.Color(255, 255, 255));
        Bt_Barang.setText("Barang");
        Bt_Barang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_BarangActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 917, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Bt_Pelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(10, 10, 10)
                    .addComponent(Bt_Barang, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(10, 10, 10)
                    .addComponent(Bt_Pesanan, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 471, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Bt_Pelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Bt_Barang, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Bt_Pesanan, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Bt_PelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_PelangganActionPerformed
        AddCust Uno = new AddCust((java.awt.Frame)this.getParent(), true);
        this.dispose();
        Uno.setVisible(true);
    }//GEN-LAST:event_Bt_PelangganActionPerformed

    private void Bt_PesananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_PesananActionPerformed
       AddOrder Doz = new AddOrder((java.awt.Frame)this.getParent(), true);
       if (orderListener != null) {
            Doz.setOrderListener(orderListener);
        }
       this.dispose(); 
       Doz.setVisible(true); 
    }//GEN-LAST:event_Bt_PesananActionPerformed

    private void Bt_BarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_BarangActionPerformed
        AddBarang Trez = new AddBarang((java.awt.Frame)this.getParent(), true);
        this.dispose(); // Tutup MainAdd sepenuhnya
        Trez.setVisible(true);
    }//GEN-LAST:event_Bt_BarangActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bt_Barang;
    private javax.swing.JButton Bt_Pelanggan;
    private javax.swing.JButton Bt_Pesanan;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
public static MainAdd getInstance() {
        return instance;
    }
}
